### ISSUE TITLE
Sheet doesn't update when sheetClass is changed programatically

### ISSUE THREAD

**Issue by arcanistzed** [League-of-Foundry-Developers/document-sheet-registrar#5]
## Steps to Reproduce

1.  Use `game.journal.get("PmZq8bbcuQaGEeoR").setFlag("core", "sheetClass", "jce.Jce")` to set a flag
2.  Sheet for Journal doesn't update

---

1.  Open configuration dialog and save
2.  Sheet updates

**Comment by zeel01** [comment]
Changing the sheet flag will not destroy the existing sheet instance and render the new app. The config application will do this on save, in order to do this from your own code you will need to manually close the sheet, delete the application from your target document, remove its sheet reference, change the flag, then render the new sheet.
